
package Frames;

import DAO.IPlacaDAO;
import DAO.PlacaDAO;
import Entidades.Placa;
import Utilidades.Encriptacion;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Rodriguez
 */
public class RecepcionDialog extends javax.swing.JDialog {

    /**
     * Creates new form RecepcionDialog
     */
    public RecepcionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        informacionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblPersona = new javax.swing.JLabel();
        lblAuto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informacionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tramite recepcion"));
        informacionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo de la placa");
        informacionPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        informacionPanel.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        lblPersona.setText("Persona:");
        informacionPanel.add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblAuto.setText("numero serie auto:");
        informacionPanel.add(lblAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        informacionPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        btnBuscar.setText("Buscar placa");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        informacionPanel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btnGenerar.setText("Generar recepcion");
        btnGenerar.setEnabled(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        informacionPanel.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        background.add(informacionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 280));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       if(camposVacios()){
            return;
        }
        
        IPlacaDAO daoplaca = new PlacaDAO();
        Placa placa = new Placa();
        placa.setCodigo(txtCodigo.getText().trim());
        
        Placa nplaca = daoplaca.obtenerPlaca(placa);
        
        if(nplaca != null) {
            btnGenerar.setEnabled(true);
            llenarCampos(nplaca);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if(camposVacios()){
            return;
        }
        
        PlacaDAO daoplaca = new PlacaDAO();
        Placa placa = new Placa();
        placa.setCodigo(txtCodigo.getText().trim());
        
        Placa nplaca = daoplaca.obtenerPlaca(placa);
        
        if(nplaca == null) {
            return;
        }
        
        nplaca.setFechaRecepcion(new GregorianCalendar());
        placa = null;
        placa = daoplaca.actualizar(nplaca);
        
        if(placa==null){
            JOptionPane.showMessageDialog(this, "SALIO MAL");
            return;
        }
            JOptionPane.showMessageDialog(this, "SALIO BIEN");
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void llenarCampos(Placa p) {
        Encriptacion encripta= new Encriptacion(); 
        
        lblPersona.setText("Persona: "+encripta.desencriptar(p.getPersona().getNombre()));
        lblAuto.setText("codigo auto: "+p.getAuto().getNserie());
    }
    
    private boolean camposVacios() {
        if(txtCodigo.getText().isBlank()) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel informacionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAuto;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
