package Frames;

import DAO.Estados;
import DAO.ILicenciaDAO;
import DAO.IPersonaDAO;
import DAO.LicenciaDAO;
import DAO.PersonaDAO;
import Entidades.Licencia;
import Entidades.Persona;
import Entidades.Tramite;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *  Clase para poder realizar el tramite de licencias
 * @author jctri
 */
public class SolicitarLicencia extends javax.swing.JFrame {

    private Persona persona;
    /**
     * IPersonaDAO para poder conectarnos a la base de datos
     */
    private IPersonaDAO daopersona;
    /**
     * Metodo constructor que recibe a una persona de referencia 
     * para realizar tramites con ella
     * @param persona 
     */
    public SolicitarLicencia(Persona persona) {
        this.persona = persona;
        initComponents();
        daopersona = new PersonaDAO();
        daopersona.refrescar(persona);
        if(persona.getDiscapacitado() == Estados.PERSONA_DISCAPACITADA) {
            txtMonto.setText("200");
        } else {
            txtMonto.setText("600");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        baner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboAños = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        botonAceptar = new swing_propio.GobiernoButton();
        btnCancelar = new swing_propio.GobiernoButton();
        txtMonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        baner.setBackground(new java.awt.Color(16, 49, 43));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitud Licencia");

        javax.swing.GroupLayout banerLayout = new javax.swing.GroupLayout(baner);
        baner.setLayout(banerLayout);
        banerLayout.setHorizontalGroup(
            banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banerLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        banerLayout.setVerticalGroup(
            banerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, banerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vigencia (Años) :");

        cboAños.setForeground(new java.awt.Color(0, 0, 0));
        cboAños.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cboAños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAñosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Monto a Pagar:");

        botonAceptar.setBackground(new java.awt.Color(255, 255, 255));
        botonAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        botonAceptar.setText("Aceptar");
        botonAceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(157, 36, 73), 2, true));
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(157, 36, 73), 2, true));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtMonto.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboAños, 0, 112, Short.MAX_VALUE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(baner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboAños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Cierra la ventana de SolicitarLicencia y nos regresa al frame Principal
     * @param evt 
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Principal pl = new Principal(true, persona);
        pl.setVisible(true);
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * Metodo para mostrar mensajes dentro del JFrame
     * @param title String titulo
     * @param message String mensaje
     * @param option int tipo de mensaje 
     */
    private void mostrarMensaje(String title, String message, int option) {
        JOptionPane.showMessageDialog(this, message, title, option);
    }
    
    private void cboAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAñosActionPerformed
        if(persona.getDiscapacitado() == Estados.PERSONA_NO_DISCAPACITADA){
            String opcion = (String) cboAños.getSelectedItem();
            switch (opcion) {
                case "1" -> txtMonto.setText("600");
                case "2" -> txtMonto.setText("900");
                case "3" -> txtMonto.setText("1100");
                default -> {
                }
            }
        }else{
            String opcion = (String) cboAños.getSelectedItem();
            switch (opcion) {
                case "1" -> txtMonto.setText("200");
                case "2" -> txtMonto.setText("500");
                case "3" -> txtMonto.setText("700");
                default -> {
                }
            }
        }
    }//GEN-LAST:event_cboAñosActionPerformed
    /**
     * Comienza el proceso para generar una licencia nueva, en caso de que ya se
     * cuente con una vieja esta se cancelara y creara una nueva
     * @param evt 
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(txtMonto.getText().isBlank()) {
            return;
        }
        ILicenciaDAO daolicencia = new LicenciaDAO();
        
        Calendar fechaLimite = new GregorianCalendar();
        fechaLimite.set( Calendar.YEAR, (fechaLimite.get(Calendar.YEAR) + cboAños.getSelectedIndex() + 1) );
        
        
        if(persona.tieneLicenciaActiva()){
            mostrarMensaje("ADVERTENCIA", "SE CANCELARA\n"
                    + "LA LICENCIA ANTERIOR", JOptionPane.WARNING_MESSAGE);
            cancelarLicenciaActiva(daolicencia);
        }

        Licencia lic = new Licencia(fechaLimite, 0, new GregorianCalendar(), new BigDecimal(txtMonto.getText()), persona, Estados.LICENCIA_VIGENTE);
        
        List<Tramite> tramites = persona.getTramites();
        tramites.add(lic);
        
        persona.setTramites(tramites);
        
        lic = daolicencia.agregarLicencia(lic);
        
        if(lic != null) {
            JOptionPane.showMessageDialog(this, "Licencia creada con exito");
            Principal pl = new Principal(true, persona);
            pl.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "no se pudo crear la licencia"
                    + " intentelo mas tarde");
        }
        daopersona.refrescar(persona);
    }//GEN-LAST:event_botonAceptarActionPerformed
    /**
     * Cancela la licencia activa de la persona precargada
     * @param dao ILicenciaDAO para poder acceder a la base de datos
     */
    private void cancelarLicenciaActiva(ILicenciaDAO dao) {
        Licencia lic = persona.obtenerLicenciaVigente();
        lic.setEstado(Estados.LICENCIA_NO_VIGENTE);
        dao.actualizar(lic);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baner;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboAños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtMonto;
    // End of variables declaration//GEN-END:variables
}
